# Optimization settings
optimization:
  n_trials: 1000
  seed: 42
  n_startup_trials: 10
  n_warmup_steps: 25
  interval_steps: 10

# Strategy Parameters
strategy_params:
  bbands:
    bb_window: [5, 300]  # (min, max)
    bb_alpha: [0.5, 4.0]
    use_sl_tp: [true, false]
    atr_window: [5, 50]
    atr_multiplier: [0.5, 10.0]
    direction: ["long", "short"]

  ma:
    fast_ma: [15, 200]
    slow_ma: [100, 500]
    direction: ["long", "short"]
    use_sl_tp: [false]
    atr_window: [5, 50]
    atr_multiplier: [0.5, 10.0]

  rsi:
    rsi_window: [5, 50]
    rsi_threshold: [10, 90]
    lookback_window: [5, 100]
    use_sl_tp: [true, false]
    atr_window: [5, 50]
    atr_multiplier: [0.5, 10.0]
    direction: ["long", "short"]

  macd:
    fast_window: [5, 100]
    slow_window: [10, 300]
    signal_window: [5, 50]
    direction: ["long", "short"]
    use_sl_tp: [true, false]
    atr_window: [5, 50]
    atr_multiplier: [0.5, 10.0]

  psar:
    af0: [0.01, 0.1]
    af_increment: [0.01, 0.1]
    max_af: [0.1, 0.5]
    direction: ["long", "short"]
    use_sl_tp: [true, false]
    atr_window: [5, 50]
    atr_multiplier: [0.5, 10.0]

  rsi_mean_reversion:
    rsi_window: [5, 200]
    rsi_lower: [20, 40]
    rsi_upper: [60, 80]
    use_sl_tp: [true, false]
    atr_window: [5, 100]
    atr_multiplier: [0.5, 10.0]
    direction: ["long", "short"]

  mean_reversion:
    bb_window: [5, 300]
    bb_alpha: [0.5, 4.0]
    timeframe_1: ["4H", "8H", "12H"]
    timeframe_2: ["16H", "24H", "32H", "48H", "72H"]
    direction: ["long", "short"]
    use_sl_tp: [true, false]
    atr_window: [5, 50]
    atr_multiplier: [0.5, 10.0]

# Data settings
data:
  in_sample_pct: 0.8
  lookback_days: 365

# Regime settings
regime:
  ma_short_window: 21
  ma_long_window: 88
  vol_short_window: 21
  avg_vol_window: 365
  target_regimes: [5, 6] # Try [1, 2] and [3, 4] and [5, 6]
