# Optimization settings
optimization:
  n_trials: 15
  seed: 42
  n_startup_trials: 50
  n_warmup_steps: 10
  interval_steps: 5
  cooldown_periods:
    "1min": 1440    # 1 day in minutes
    "5min": 288     # 1 day in 5-min periods
    "15min": 96     # 1 day in 15-min periods
    "30min": 48     # 1 day in 30-min periods
    "60min": 24     # 1 day in hours
    "4H": 6         # 1 day in 4-hour periods
    "1D": 1         # 1 day in days

# Objective function settings
objective:
  type: "weighted_avg"  # Options: calmar_ratio, sharpe_ratio, sortino_ratio, omega_ratio, total_return, win_rate, profit_factor, weighted_avg
  trade_weight: 0.1     # Weight for number of trades in objective (0.0 to 1.0)
  min_trades: 20        # Minimum number of trades required for valid strategy
  metrics:              # Only used when type is "weighted_avg"
    calmar_ratio:
      description: "Returns/max drawdown - good for drawdown-sensitive strategies"
      weight: 0.30
    sharpe_ratio:
      description: "Returns/volatility - good for risk-adjusted performance"
      weight: 0.10
    sortino_ratio:
      description: "Similar to Sharpe but only penalizes downside volatility"
      weight: 0.10
    omega_ratio:
      description: "Probability weighted ratio of gains vs losses"
      weight: 0.0
    total_return:
      description: "Simple returns - good for pure performance"
      weight: 0.30
    win_rate:
      description: "Pure win rate - but beware of small gains vs large losses"
      weight: 0.20
    profit_factor:
      description: "Gross profits/gross losses - good for consistent profitability"
      weight: 0.10

# Strategy Parameters
strategy_params:
  bbands:
    bb_window: [3, 500]  # Wider range
    bb_alpha: [0.1, 10.0]  # Wider range
    use_sl_tp: [true, false]
    atr_window: [3, 100]  # Wider range
    atr_multiplier: [0.1, 20.0]  # Wider range
    direction: ["long", "short"]
    cooldown_period: [0, 48]  # Integer range from no cooldown to 2 days (hourly data)

  ma:
    fast_ma: [5, 300]  # Wider range
    slow_ma: [50, 1000]  # Wider range
    direction: ["long", "short"]
    use_sl_tp: [false]
    atr_window: [3, 100]  # Wider range
    atr_multiplier: [0.1, 20.0]  # Wider range
    cooldown_period: [0, 48]  # Integer range

  rsi:
    rsi_window: [3, 100]  # Wider range
    rsi_threshold: [5, 95]  # Wider range
    lookback_window: [3, 200]  # Wider range
    use_sl_tp: [true, false]
    atr_window: [3, 100]  # Wider range
    atr_multiplier: [0.1, 20.0]  # Wider range
    direction: ["long", "short"]
    cooldown_period: [0, 48]  # Integer range

  macd:
    fast_window: [3, 200]  # Wider range
    slow_window: [5, 500]  # Wider range
    signal_window: [3, 100]  # Wider range
    direction: ["long", "short"]
    use_sl_tp: [true, false]
    atr_window: [3, 100]  # Wider range
    atr_multiplier: [0.1, 20.0]  # Wider range
    cooldown_period: [0, 48]  # Integer range

  psar:
    af0: [0.001, 0.2]  # Wider range
    af_increment: [0.001, 0.2]  # Wider range
    max_af: [0.05, 1.0]  # Wider range
    direction: ["long", "short"]
    use_sl_tp: [true, false]
    atr_window: [3, 100]  # Wider range
    atr_multiplier: [0.1, 20.0]  # Wider range
    cooldown_period: [0, 48]  # Integer range

  rsi_mean_reversion:
    rsi_window: [3, 300]  # Wider range
    rsi_lower: [10, 45]  # Wider range
    rsi_upper: [55, 90]  # Wider range
    use_sl_tp: [true, false]
    atr_window: [3, 200]  # Wider range
    atr_multiplier: [0.1, 20.0]  # Wider range
    direction: ["long", "short"]
    cooldown_period: [0, 48]  # Integer range

  mean_reversion:
    bb_window: [3, 500]  # Wider range
    bb_alpha: [0.1, 10.0]  # Wider range
    timeframe_1: ["1H", "2H", "4H", "8H", "12H"]  # Added more timeframes
    timeframe_2: ["16H", "24H", "32H", "48H", "72H", "96H", "120H"]  # Added more timeframes
    direction: ["long", "short"]
    use_sl_tp: [true, false]
    atr_window: [3, 100]  # Wider range
    atr_multiplier: [0.1, 20.0]  # Wider range
    cooldown_period: [0, 48]  # Integer range

# Data settings
data:
  in_sample_pct: 0.7
  lookback_days: 365

# Regime settings
regime:
  ma_short_window: 21
  ma_long_window: 88
  vol_short_window: 21
  avg_vol_window: 365
  target_regimes: [1, 2]

timeframes:
  base: "1min"
  analysis: "60min"
  regime: "1D"